services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend/static:/app/static
      - ./frontend/templates:/app/templates

  backend:
    environment:
      DB_ADDRESS: postgres-db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
      - "8000:8000"
    networks:
      - app-network

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_init:/docker-entrypoint-initdb.d
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
